### ISSUE TITLE
Implement archival operation against mock

### ISSUE THREAD

**Issue by phwissmann** [SwissOpenEM/ScopeMArchiver#17]
Goal of this story is to implement operations on the dataset and the interaction with the LTS. 

**Tasks to implement:**

- [ ]  Create datablocks
- [ ]  Cleanup/restore datablocks (failure case)
- [ ]  Move datablocks to staging
- [ ]  Cleanup staging (failure case)
- [ ]  Move datablocks to LTS
- [ ]  Validate datablocks

**LTS Constraints:**
- file size
- path length
- delay action timer

**Definition of done:**
Service is  deployed an archiving pipeline for an existing dataset can be triggered and the dataset is archived against a mock implementation of the LTS
