### ISSUE TITLE
[Epic] Frontend

### ISSUE THREAD

**Issue by phwissmann** [SwissOpenEM/ScopeMArchiver#34]
In order for the users to upload data to the ETH LTS or PSI, register datasets with PSI and annotate the metadata of the datasets, a frontend is needed. The users shall be able to login with their institution's credentials. Only one login should be required. 

- [ ] Decide (frontend) on technologies
- [ ] [ETH] Implement data uploading
- [ ] Add metadata annotation (and extraction?)
- [ ] Add Authentication
