### ISSUE TITLE
[Feature] Design authentication for user flow

### ISSUE THREAD

**Issue by phwissmann** [SwissOpenEM/ScopeMArchiver#46]
**Description**
As a user I want to log in once in Scicat/the frontend when ingesting, archiving and retrieving datasets.
As an admin/developer I want all calls between Scicat and the archiver backend and between SciCat and the Prefect flows to be authenticated as well as any calls between the ingestor and the backend/minio.

The following API calls need authentication
- Ingestor -> archiver backend
  - The ingestor will add a jwt token retrieved from the OIDC provider to any API calls. The token needs to be verify against a validation endpoint
- Ingestor -> Minio 
  - The ingestor will retrieve presigned urls from the archiver-backend for any calls to Minio 
- Ingestor -> Scicat
  - Not in scope. Done through Scicat login 
- Scicat -> Backend
  - To be investigated. Any authentication needs to be added to the urlAction in Scicat. Potentially pre shared secret works.
- Prefect -> Scicat
  - Client credentials flow with dedicated user for ethz archiving service
- Prefect -> Minio
  - Dedicated service user defined in Minio

**Task**
- [ ] Add access token to requests towards archiver backend (fastapi) from ingestor (openapi.yml)
- [ ] Archiver backend (fastapi): require jwt token and verify against configurable keycloak instance
- [ ] Scicat-> Archiver backend: add authentication to /archiver/jobs endpoint @pulsargranular 
- [ ] Add `Authorization` header to urlaction in scicat @phwissmann

**Comment by phwissmann** [comment]
> for technical reasons, the ingestor is a standalone-app, not running in a browser. Which means we can redirect the user to the authentication infrastructure, but there is no way back

The frontend will authenticate and send a jwt token to the ingestor. The ingestor then validates the token and could use it in the requests to the archiver service. I am not sure if/how device auth flow could help.
